### ISSUE TITLE
Draft of basic scenarios for demo time PFS & MS

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/raiden-services#107]
## Problem Definition

When we have a demo, we want to show integrated PFS and MS features. Therefore, we can use the scenario player to create basic scenarios that test all these new features. 

In this example we have a basic topology `0 <-> 1 <-> 2` and deposit tokens into the channel, always on that side of the channel with the smaller number. 

Now we would see in the pathfinding service logs:
- a request for a route that will fail (2 -> 1 -> 0)
- a request for a route that will return a route (does node 1 actually also request the pfs again, even if the target is the direct channel partner?)

... and in the monitoring service logs:
- a channel to be closed when the channel partner is offline to see the monitoring service updating the balance proof on-chain (to be checked on Etherscan)

## Actual Outcome

```
version: 2

settings:
  gas_price: "fast"
  chain: kovan

token:

nodes:
  mode: managed
  count: 3
  raiden_version: /home/pirate/raiden/venv/raiden/bin/raiden
  default_options:
    gas-price: fast
    pathfinding-service-address: "https://pfs-kovan.services-dev.raiden.network"

scenario:
  serial:
    tasks:
      - parallel:
          name: "Open channels"
          tasks:
            - open_channel: {from: 0, to: 1, total_deposit: 10}
            - open_channel: {from: 1, to: 2, total_deposit: 10}

      - serial:
          name: "Trying an impossible transfer - pfs should not provide a route"
          ## We can check in the pathfinding service logs to see if a path was requested and no path was returned
          tasks:
            - transfer: {from: 2, to: 0, amount: 5, expected_http_status: 409}
            - wait: 1000
            - assert: {from: 0, to: 1, balance: 10}
            - assert: {from: 1, to: 0, balance: 0}
            - assert: {from: 1, to: 2, balance: 10}
            - assert: {from: 2, to: 1, balance: 0}

      - serial:
          name: "Trying a possible transfer - pfs should provide a route"
          ## We can check in the pathfinding service logs to see if a path was requested and a path was returned
          tasks:
            - transfer: {from: 0, to: 2, amount: 5}
            - wait: 1000
            - assert: {from: 0, to: 1, balance: 5}
            - assert: {from: 1, to: 0, balance: 5}
            - assert: {from: 1, to: 2, balance: 5}
            - assert: {from: 2, to: 1, balance: 5}

      - serial:
          name: "Killing node 2, then node 1 closes the channel"
          ## We can check if the monitoring service reacts to the channel closing
          tasks:
            - stop_node: 2
            - close_channel: {from: 1, to: 2}
            - wait: 1000
```
